### PR TITLE
keep presets list up to date with IndexDB values

### PR DESCRIPTION
**Pull request by danielrobertson**
@ZachYanez Here is one approach on how to keep the **Presets** dropdown current with IndexDB, by keeping the list current in local state, updating that list with IndexDB values on the initial render with a `useEffect`, and then appending values _one at a time_ as the user adds values. 

The alternative on this which I coded but opted not show is a _bit_ trickier, which is to write new presets to IndexDB and then run a "refresh" routine to overwrite local state `presets` with the values that are currently in IndexDB, which is prone to infinite loops/re-renders

One other random unsolicited feedback is to get eslint/prettier plugins going on this project to keep formatting consistent. Super easy in VSCode editor, which I assume you're using

Screen Recording 2021-02-02 at 10 55 39 AM

### CODE REVIEW

**Comment by ZachYanez** [comment]
@danielrobertson That is exactly it! Holy hot dang. Yesterday I got the add to work, which is what was initially tripping me up, and then today I was going to tackle pretty much what you did in useEffect.

**Comment by ZachYanez** [comment]
@danielrobertson I love what you did in 31-45, that's what I kinda had in my head, but SEEING it done helps me understand the flow really well. The concept of returning and then mapping over is huge and to see it done so elegantly is great.

**Comment by ZachYanez** [comment]
@danielrobertson https://www.npmjs.com/package/react-indexed-db

**Review by ZachYanez — APPROVED** [review]

**Comment by ZachYanez** [comment]
@danielrobertson Getting a weird error after I tried to merge it. I thought I merged ok, but this is popping up. Maybe we could do a virtual thing later, or if you know what to I can fix it.


Screen Shot 2021-02-02 at 12 41 35 PM

**Comment by danielrobertson** [comment]
> @danielrobertson Getting a weird error after I tried to merge it. I thought I merged ok, but this is popping up. Maybe we could do a virtual thing later, or if you know what to I can fix it.
> 
> Screen Shot 2021-02-02 at 12 41 35 PM

@ZachYanez Oops, this is my bad because locally I had a separate file in `/src` with an exported array of initial values called `initialPresets` but then when I realized I don't have github push permission for your repo, I use the GitHub web fork functionality and decided last minute to switch the separate file into simply the INITIAL_PRESETS array that's at the top of the file. Replace `initialPresets` with INITIAL_PRESETS, that's all it is

**Comment by ZachYanez** [comment]
Ok word. I wondered if that was the fix. Appreciate it 🙌🏽

**Pull request closed without merging**
